inherit_gem:
  lint-config-cc:
    - default.yml

AllCops:
  Exclude:
    - bin/**/*
  TargetRubyVersion: 2.1
Bundler/DuplicatedGem:
  Enabled: false
Metrics/LineLength:
  Exclude:
    - Gemfile
Style/OptionHash:
  Enabled: false
Style/VariableNumber:
  EnforcedStyle: snake_case
