inherit_from:
  - ../.rubocop.yml

Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Lint/HandleExceptions:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
